version: '3.7'

services:
    api-gateway:
        image: nginx:latest
        volumes:
            - ./api-gateway/default.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80

    food-service:
        image: asia.gcr.io/project-eatsme-backend/food-service:cfeed5b807e9a553897f7bfa60dca63f26de752b
        volumes:
            - ./services/graphql/src:/food-service/src
        env_file:
            - ./services/graphql/.env.docker

    road-service:
        build:
            context: ./services/restAPI
            dockerfile: DockerFile
        volumes:
            - ./services/restAPI/src:/road-service/src
        env_file:
            - ./services/restAPI/.env.docker

    eatsme-mysql:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: 'eatsMe'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - 3306:3306

    eatsme-mongodb:
        image: mongo:5
        ports:
            - 27017:27017

    eatme-redis:
        image: redis:latest
        ports:
            - 6379:6379
