version: "3.7"

services:
  # api-gateway:
  #     image: asia.gcr.io/project-eatsme-backend/api-gateway:0.2
  #     build:
  #         context: api-gateway
  #         dockerfile: DockerFile
  #     env_file:
  #         - .env
  #     ports:
  #         - 80:80

  # food-service:
  #     image: asia.gcr.io/project-eatsme-backend/food-service:0.4
  #     build:
  #         context: services/graphql/
  #         dockerfile: DockerFile
  #     env_file:
  #         - .env

  road-service:
    image: asia.gcr.io/project-eatsme-backend/road-service:0.6
    build:
      context: services/restAPI/
      dockerfile: DockerFile
    env_file:
      - .env
