version: '3.7'

services:
    api-gateway:
        image: asia.gcr.io/project-eatsme-backend/api-gateway:0.1
        build:
            context: ./api-gateway/
            dockerfile: DockerFile.prod
        ports:
            - 80:80

    food-service:
        image: asia.gcr.io/project-eatsme-backend/food-service:0.1
        build:
            context: ./services/graphql
            dockerfile: DockerFile.prod
        env_file:
            - .env

    road-service:
        image: asia.gcr.io/project-eatsme-backend/road-service:0.1
        build:
            context: ./services/restAPI
            dockerfile: DockerFile.prod
        env_file:
            - .env

    mysql:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: eatsMe
            MYSQL_ROOT_PASSWORD: root
        env_file:
            - .env
        ports:
            - 3306:3306

    mongodb:
        image: mongo:5
        env_file:
            - .env
        ports:
            - 27017:27017

    redis:
        image: redis:latest
        env_file:
            - .env
        ports:
            - 6379:6379
