version: '3.7'

services:
    # api-gateway:
    #     image: asia.gcr.io/eatsme/api-gateway:0.0
    #     build:
    #         context: api-gateway
    #         dockerfile: DockerFile
    #     env_file:
    #         - .env
    #     ports:
    #         - 80:80

    food-service:
        image: asia.gcr.io/eatsme/food-service:0.7
        build:
            context: services/graphql/
            dockerfile: DockerFile
        env_file:
            - .env

    road-service:
        image: asia.gcr.io/eatsme/road-service:0.4
        build:
            context: services/restAPI/
            dockerfile: DockerFile
        env_file:
            - .env
