name: Deploy to GCP VM

on:
  workflow_dispatch: 
  push:
    branches:
      - master
      
jobs:
  deploy:
    name: Setup, Build, Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Update VM with new image
      run: |-
        gcloud compute ssh --project=${{ secrets.GCP_PROJECT_ID }} --zone=${{ secrets.GCP_ZONE }} ${{ secrets.GCP_VM_NAME }}
        pwd
        cd ..
        cd ..
        ls
        sudo docker service update --image ${{secrets.GCP_REGION}}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY}}:${{ github.sha }} eatsme_api-gateway
