name: Deploy to GCP VM

on:
  workflow_dispatch: 
  push:
    branches:
      - master
      
jobs:
  deploy:
    name: Setup, Build, Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Build tag Docker image
      run: |-
        pwd
        gcloud auth configure-docker
        cd api-gateway
        docker build -t ${{ secrets.GCP_REGION }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY}}:${{ github.sha }} -f ./DockerFile .
    
    - name: push tag Docker image
      run: |-
        whoami
        sudo usermod -aG docker runner
        docker push ${{secrets.GCP_REGION}}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY}}:${{ github.sha }}
    
    - name: Update VM with new image
      run: |-
        docker service update --image ${{secrets.GCP_REGION}}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY}}:${{ github.sha }} eatsme_api-gateway
