name: EatsMe - Deploy to GCP VM

on:
  workflow_dispatch: 
  push:
    branches:
      - master
      
env:
  # GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }} 
  GCP_ZONE: ${{ secrets.GCP_ZONE }}  
  GCP_VM_NAME: ${{ secrets.GCP_VM_NAME }} 
  IMAGE: ${{ secrets.GCP_API_GATEWAY }}       
      
jobs:
  eatsme-deploy:
    name: eatsme-deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: api-gateway Build tag Docker image
      run: |-
        gcloud auth configure-docker
        cd api-gateway
        docker build -t "$GCP_REGION/$GCP_PROJECT_ID/$IMAGE:$GITHUB_SHA -f ./DockerFile ."
      
    - name: api-gateway push tag Docker image
      run: |-
        docker push "$GCP_REGION/$GCP_PROJECT_ID/$IMAGE:$GITHUB_SHA"
        
    - name: api-gateway Update VM with new image
      run: |-
        gcloud compute ssh --project="$GCP_PROJECT_ID" --zone="$GCP_ZONE" "$GCP_VM_NAME" \
        --command "docker service update --update-delay 5m --with-registry-auth --image $GCP_REGION/$GCP_PROJECT_ID/$IMAGE:$GITHUB_SHA eatsme_api-gateway"
    



