name: EatsMe - Deploy to GCP VM

on:
    workflow_dispatch:
    push:
        branches:
            - dev
            - master

jobs:
    eatsme-deploy:
        name: Api-gateway-eatsme-deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - id: 'auth'
              name: 'Authenticate to Google Cloud'
              uses: 'google-github-actions/auth@v0'
              with:
                  credentials_json: ${{ secrets.GCP_CREDENTIALS }}

            - name: api-gateway Build tag Docker image
              run: |-
                  gcloud auth configure-docker
                  cd api-gateway
                  docker build -t ${{ secrets.GCP_REGION }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_API_GATEWAY }}:${{ github.sha }} -f ./DockerFile .
            - name: api-gateway push tag Docker image
              run: |-
                  docker push ${{ secrets.GCP_REGION }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_API_GATEWAY }}:${{ github.sha }}
            - name: api-gateway Update VM with new image
              run: |-
                  gcloud compute ssh --project=${{ secrets.GCP_PROJECT_ID }} --zone=${{ secrets.GCP_ZONE }} ${{ secrets.GCP_VM_NAME }}@${{ secrets.GCP_VM_NAME }} \
                  --command "docker image prune -a" \
                  --command "docker service update --update-delay 5m --with-registry-auth --image ${{ secrets.GCP_REGION }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_API_GATEWAY }}:${{ github.sha }} eatsme_api-gateway"
