name: EatsMe - Food-service Deploy to GCP VM

on:
    workflow_dispatch:
    push:
        branches:
            - dev
            - master

jobs:
    Food-service-deploy:
        name: Food-service-deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - id: 'auth'
              name: 'Authenticate to Google Cloud'
              uses: 'google-github-actions/auth@v0'
              with:
                  credentials_json: ${{ secrets.GCP_CREDENTIALS }}
                  export_default_credentials: true

            - name: Food-service Build tag Docker image
              run: |-
                  echo ${{ secrets.GCP_FILE_STORAGE }} > gcp-file-storage.json
                  gcloud auth activate-service-account --key-file=gcp-credentials.json
                  gcloud auth configure-docker
                  cd services/graphql
                  touch .gcp-file-storage.json
                  docker build -t ${{ secrets.GCP_REGION }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_FOOD_SERVICE }}:${{ github.sha }} -f ./DockerFile .
            - name: Food-service push tag Docker image
              run: |-
                  docker push ${{ secrets.GCP_REGION }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_FOOD_SERVICE }}:${{ github.sha }}
            - name: Food-service Update VM with new image
              run: |-
                  gcloud compute ssh --project=${{ secrets.GCP_PROJECT_ID }} --zone=${{ secrets.GCP_ZONE }} ${{ secrets.GCP_VM_NAME }}@${{ secrets.GCP_VM_NAME }} \
                  --command "docker image prune -a" \
                  --command "docker service update --update-delay 5m --with-registry-auth --image ${{ secrets.GCP_REGION }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_FOOD_SERVICE }}:${{ github.sha }} eatsme_food-service"
