name: EatsMe - food Deploy to GCP VM

on:
  workflow_dispatch: 
  pull_request:
    branches:
      - master
      
jobs:
  food-service-deploy:
    name: food-service-deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
 
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    
    - name: food-service Build tag Docker image
      run: |-
        gcloud auth configure-docker
        cd services/graphql
        docker build -t ${{ secrets.GCP_REGION }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_FOOD_SERVICE}}:${{ github.sha }} -f ./DockerFile .
    
    - name: food-service push tag Docker image
      run: |-
        docker image ls
        docker push ${{secrets.GCP_REGION}}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_FOOD_SERVICE}}:${{ github.sha }}
    
    - name: food-service Update VM with new image
      run: |-
        gcloud compute ssh --project=${{ secrets.GCP_PROJECT_ID }} --zone=${{ secrets.GCP_ZONE }} ${{ secrets.GCP_VM_NAME }} \
        --command "sudo su -" \        
        --command "sudo docker image prune -a" \
        --command "docker service update --update-delay 5m --with-registry-auth --image ${{ secrets.GCP_REGION }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_FOOD_SERVICE}}:${{ github.sha }} eatsme_food-service"
    
   
